# Generated by Django 5.0.6 on 2024-08-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='ABARCA_OTRA_PROVINCIA',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='PROVINCIA2',
        ),
    ]
