# Generated by Django 5.0.6 on 2024-08-14 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0002_remove_propuesta_abarca_otra_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='FORMULARIO_FINANCIAMIENTO',
            field=models.FileField(blank=True, null=True, upload_to='formularios/'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='empresa_que_financia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_financiadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
