# Generated by Django 5.0.6 on 2024-08-14 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0003_propuesta_formulario_financiamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='propuestas_financiadas',
            field=models.ManyToManyField(blank=True, related_name='empresas_que_financiaron', to='propuestas.propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='empresa_que_financia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_que_financio', to=settings.AUTH_USER_MODEL),
        ),
    ]
