# Generated by Django 5.0.6 on 2024-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0004_usuario_propuestas_financiadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='llamado_a_licitacion',
            field=models.BooleanField(default=False),
        ),
    ]
