# Generated by Django 5.0.6 on 2024-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0005_propuesta_llamado_a_licitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='empresa_financiadora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
