# Generated by Django 5.0.6 on 2024-08-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0006_propuesta_empresa_financiadora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='empresa_que_financia',
        ),
    ]
