# Generated by Django 5.0.6 on 2024-08-15 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0007_remove_propuesta_empresa_que_financia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='empresa_financiadora',
        ),
        migrations.AddField(
            model_name='propuesta',
            name='empresas_que_financian',
            field=models.ManyToManyField(blank=True, related_name='empresas_financiadoras', to=settings.AUTH_USER_MODEL),
        ),
    ]
