# Generated by Django 5.0.6 on 2024-08-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0010_comment_delete_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuestas.propuesta'),
        ),
    ]
